pizzamama/main/urls.py
from django.urls import path
from . import views

#this "namesapce" allows the html to call a specific view according to this name
app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/menu/urls.py
from django.urls import path
from . import views

app_name = "menu"

urlpatterns = [
    path('', views.index, name="index"),
]

pizzamama/pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pizza-menu/', include('menu.urls')),
    path('', include('main.urls')),
]

pizzamama/main/models.py
from django.db import models

# Create your models here.

pizzamama/menu/models.py
from django.db import models

class Pizza(models.Model):
    name = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    price = models.FloatField(default=0)
    vegetarian = models.BooleanField(default=False)
    glutenfree = models.BooleanField(default=False)

    def __str__(self):
        return self.name

pizzamama/main/views.py
from django.shortcuts import render

# only needed if you use the HttpResponse class
#from django.http import HttpResponse


# Create your views here.



### this will change to return the render like the menu view file.. then you'll need to load the app in the settings file too..
def  index(request):
    return render(request, "main/index.html")

pizzamama/menu/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Pizza

# Create your views here.

def index(request, name="index"):
    pizzas = Pizza.objects.all().order_by('price')
    

    # pizzas_names = [pizza.name + " : " + "€" + str(pizza.price) for pizza in  pizzas]
    # pizzas_names_str = ", ".join(pizzas_names)
    
    # title = "Our Pizza's:  "

    # return HttpResponse(title + pizzas_names_str)

    
    return render(request, "menu/index.html", {'pizzas': pizzas}) #the 'pizzas' in parenth is the name used in the html file
    
    #{'veg': veg}

    
    
    

pizzamama/main/templates/main/index.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>My Index Page</title>
        <link rel="stylesheet" href="{% static '/main/style.css' %}">

    </head>
    <body>
        <img id="small_logo" src="{% static '/main/images/cyber.png' %}"/>
        <a href="{% url 'menu:index' %}">THIS IS A LINK</a>
    </body>
</html>

pizzamama/menu/templates/menu/index.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>My Index Page</title>
        <link rel="stylesheet" href="{% static '/menu/style.css' %}">

    </head>
    <body>
        <img id="small_logo" src="{% static '/menu/images/cyber.png' %}"/>
        <h1> Our Pizza</h1>
        <ul>
            {% for pizza in pizzas %}
            <!-- the double curly brackets syntax will convert the price float to string to display..-->
            <li>{{pizza.name}} - €{{pizza.price | floatformat:2}} - 
                <div>
                    {{pizza.ingredients}}
                </div>
                <div>
                    {% if pizza.vegetarian %}
                        <span>Vegetarian*</span>
                    {% endif %}
                </div>
                <div>
                    {% if pizza.glutenfree %}
                        <span>Gluten Free!*</span>
                    {% endif %}
                </div>

            </li>

            {% endfor %}
        </ul>
    </body>
</html>